SELECT CC.ID AS activity_id,
       TO_UTC_TIMESTAMP(CC.START_TM, 'GMT+8') AS start_tm,
       TO_UTC_TIMESTAMP(CC.END_TM, 'GMT+8') AS end_tm,
       TO_UTC_TIMESTAMP(CC.CREATE_TM, 'GMT+8') AS activity_create_tm,
       CC.ACTIVITY_NAME AS activity_name,
       CC.ACTIVITY_TYPE AS activity_type_code,
       ACTIVITY_TYPE.CODE_VALUE AS activity_type_value,
       CC.GRANT_OBJ AS grant_obj_code,
       GRANT_OBJ.CODE_VALUE AS grant_obj_value,
       (BB.NOT_GRANTED + BB.GRANTED + BB.USED + BB.REMOVED + BB.EXPIRED) total,
       (BB.GRANTED + BB.USED + BB.EXPIRED) granted
  FROM (SELECT ACTIVITY_ID,
               SUM(CASE WHEN AA.FLAG = 1 THEN 1 ELSE 0 END) NOT_GRANTED,
               SUM(CASE WHEN AA.FLAG = 2 THEN 1 ELSE 0 END) GRANTED,
               SUM(CASE WHEN AA.FLAG = 3 THEN 1 ELSE 0 END) USED,
               SUM(CASE WHEN AA.FLAG = 4 THEN 1 ELSE 0 END) REMOVED,
               SUM(CASE WHEN AA.FLAG = 5 THEN 1 ELSE 0 END) EXPIRED
          FROM FACT_EDM_ACTIVITY_COUPON_POOL AA
         GROUP BY ACTIVITY_ID) BB
 INNER JOIN DIM_EDM_ACTIVITY CC ON BB.ACTIVITY_ID = CC.ID
LEFT JOIN (SELECT CODE_VALUE,CODE_CODE FROM DIM_EDM_CODE WHERE CODE_TYPE = 'ACTIVITY_TYPE') AS ACTIVITY_TYPE ON ACTIVITY_TYPE.CODE_CODE = CC.ACTIVITY_TYPE
LEFT JOIN (SELECT CODE_VALUE,CODE_CODE FROM DIM_EDM_CODE WHERE CODE_TYPE = 'GRANT_OBJ') AS GRANT_OBJ ON GRANT_OBJ.CODE_CODE = CC.GRANT_OBJ
